# Rubygems broke build for rvm 1.8.7
# Temporary workound until https://github.com/rubygems/rubygems/pull/763 is merged
before_install:
  - gem update --system 2.1.11
  - gem --version
language: ruby
script: "bundle exec rspec"
notifications:
  email: false
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
